import { MenuItemObj } from '@/types';
import {
  Person,
  LocationOn,
  Storefront,
  Work,
  RequestPage,
  Report,
  Comment,
  Analytics,
  Settings,
} from '@mui/icons-material';

export const languageMenuItems = [
  { icon: 'images/icons/en.svg', key: 'en', text: 'English' },
  { icon: 'images/icons/es.svg', key: 'es', text: 'Español' },
];

export const superSidebarItems: MenuItemObj[] = [
  {
    id: 1,
    text: 'Users',
    isSelected: false,
    icon: <Person sx={{ marginRight: 2 }} />,
    dropdown: [
      {
        text: 'Customers',
        route: 'users/customers',
        isSelected: false,
      },
      {
        text: 'Tablets',
        route: 'users/tablets',
        isSelected: false,
      },
      {
        text: 'Admins',
        route: 'users/admins',
        isSelected: false,
      },
      {
        text: 'Invitations',
        route: 'users/invitations',
        disabled: true,
        isSelected: false,
      },
    ],
  },
  {
    id: 2,
    text: 'Locations',
    route: 'locations',
    isSelected: false,
    icon: <LocationOn sx={{ marginRight: 2 }} />,
  },
  {
    id: 3,
    text: 'Products',
    route: 'products',
    isSelected: false,
    icon: <Storefront sx={{ marginRight: 2 }} />,
  },
  {
    id: 4,
    text: 'Rewards',
    route: 'rewards',
    isSelected: false,
    icon: <Work sx={{ marginRight: 2 }} />,
  },
  {
    id: 5,
    text: 'Request',
    route: 'requests',
    isSelected: false,
    icon: <RequestPage sx={{ marginRight: 2 }} />,
  },

  {
    id: 6,
    text: 'Reports',
    isSelected: false,
    icon: <Report sx={{ marginRight: 2 }} />,
    dropdown: [
      {
        text: 'Activity',
        route: 'activity',
        isSelected: false,
      },
      {
        text: 'Transaction',
        route: 'transactions',
        isSelected: false,
      },
    ],
  },
  {
    id: 7,
    text: 'Comments',
    route: 'comments',
    isSelected: false,
    icon: <Comment sx={{ marginRight: 2 }} />,
    disabled: true,
  },
  {
    id: 8,
    text: 'Analytics',
    isSelected: false,
    icon: <Analytics sx={{ marginRight: 2 }} />,
    route: 'analytics',
    disabled: true,
  },
  {
    id: 9,
    text: 'Site Settings',
    route: 'settings',
    disabled: true,
    isSelected: false,
    icon: <Settings sx={{ marginRight: 2 }} />,
  },
];

export const notificationData = [
  {
    id: 1,
    model: 'USER',
    type: 'CREATE',
    data: {
      id: 2,
      firstName: 'Alexa',
      lastName: 'Liras',
      email: 'alexa@gmail.com',
      phonenumber: '+14898903328',
      birthday: '12/06/1971',
      role: 4,
      status: 1,
      createdAt: '16/09/2021',
      asset: '',
      location: {
        address1: '96607 Claire Square Suite',
        address2: 'St. Louis Park, HI',
        city: 'New York',
        state: '',
        country: 'USA',
        zipcode: '48021',
      },
    },
    createdAt: '2022/12/13',
    updatedAt: '2022/12/13',
  },
  {
    id: 2,
    model: 'REQUEST',
    type: 'CREATE',
    data: {
      id: 1,
      item: {
        id: 6,
        name: 'Marshal V6',
        urls: ['/images/marshal.jpg'],
        location: {
          name: 'Palm Casino Resort',
          coordinates: { lat: 40.7127837, lng: -74.0059413 },
          id: 1,
          location: {
            address1: '',
            address2: '',
            city: '',
            state: 'New York',
            zipcode: '',
            country: 'USA',
          },
          status: true,
          type: 'Palm',
          urls: [
            '/images/palm.png',
            '/images/roulette.png',
            '/images/palm.png',
            '/images/roulette.png',
          ],
        },
        point: 39000,
        short: '128gb RAM $600',
        description: '',
        amount: 3,
        status: 'Available',
        createdAt: '14/06/2022',
      },
      user: {
        id: 1,
        firstName: 'Esthera',
        lastName: 'Jackson',
        email: 'alecthompson@mail.com',
        phonenumber: '+14898903328',
        birthday: '14/06/1991',
        role: 4,
        status: 1,
        createdAt: '17/09/2021',
        asset: '',
        location: {
          address1: '96607 Claire Square Suite',
          address2: 'St. Louis Park, HI',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '48021',
        },
      },
      location: {
        name: 'Palm Casino Resort',
        coordinates: { lat: 40.7127837, lng: -74.0059413 },
        id: 1,
        location: {
          address1: '',
          address2: '',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '',
        },
        status: true,
        type: 'Palm',
        urls: [
          'images/palm.png',
          'images/roulette.png',
          'images/palm.png',
          'images/roulette.png',
        ],
      },
      status: 'Waiting',
      requestedAt: '14/06/2022',
    },
    createdAt: '2022/12/12',
    updatedAt: '2022/12/13',
  },
];
