export * as authApi from './auth.api';
export * as assetApi from './asset.api';
export * as userApi from './user.api';
export * as locationApi from './location.api';
export * as pointApi from './point.api';
export * as productApi from './product.api';
export * as rewardApi from './reward.api';
export * as activityApi from './activity.api';
export * as configApi from './config.api';
export * as tabletApi from './tablet.api';
export * as transactionApi from './transaction.api';
export * as emailTemplateApi from './emailTemplate.api';
export * as campaignApi from './campaign.api';
export { jwtAxios, setupJwt } from './axios.api';
