import { ActivityModel, ActivityType, ProductStatus } from '@/constants';
import { ActivityItemType } from '@/types';

export const activityData: ActivityItemType[] = [
  // {
  //   id: 1,
  //   user: {
  //     id: 2,
  //     firstName: 'Alexa',
  //     lastName: 'Liras',
  //     email: 'alexa@gmail.com',
  //     phone: '+14898903328',
  //     birthday: '12/06/1971',
  //     role: 4,
  //     status: 1,
  //     createdAt: '16/09/2021',
  //     asset: '',
  //     address: {
  //       address1: '96607 Claire Square Suite',
  //       address2: 'St. Louis Park, HI',
  //       city: 'New York',
  //       state: '',
  //       country: 'USA',
  //       zipcode: '48021',
  //     },
  //   },
  //   victim: {
  //     name: 'Palm Casino Resort',
  //     coords: { lat: 40.7127837, lng: -74.0059413 },
  //     id: 1,
  //     address: {
  //       address1: '',
  //       address2: '',
  //       city: '',
  //       state: 'New York',
  //       zipcode: '',
  //       country: 'USA',
  //     },
  //     status: 'OPEN',
  //     type: 'Palm',
  //   },
  //   model: ActivityModel.USER,
  //   type: ActivityType.CHECKIN,
  //   status: '1000 Point',
  //   createdAt: '2022/11/22',
  // },
  // {
  //   id: 2,
  //   user: {
  //     id: 2,
  //     firstName: 'Alexa',
  //     lastName: 'Liras',
  //     email: 'alexa@gmail.com',
  //     phone: '+14898903328',
  //     birthday: '12/06/1971',
  //     role: 4,
  //     status: 1,
  //     createdAt: '16/09/2021',
  //     asset: '',
  //     address: {
  //       address1: '96607 Claire Square Suite',
  //       address2: 'St. Louis Park, HI',
  //       city: 'New York',
  //       state: '',
  //       country: 'USA',
  //       zipcode: '48021',
  //     },
  //   },
  //   victim: {
  //     id: 1,
  //     item: {
  //       id: 6,
  //       product: {
  //         id: 6,
  //         name: 'Marshal V6',
  //         point: 39000,
  //         short: '128gb RAM $600',
  //         description: '',
  //         amount: 3,
  //         status: ProductStatus.AVAILABLE,
  //         createdAt: '14/06/2022',
  //       },
  //       locationId: 0,
  //       location: {
  //         name: 'Palm Casino Resort',
  //         coords: { lat: 40.7127837, lng: -74.0059413 },
  //         id: 1,
  //         address: {
  //           address1: '',
  //           address2: '',
  //           city: '',
  //           state: 'New York',
  //           zipcode: '',
  //           country: 'USA',
  //         },
  //         status: 'OPEN',
  //         type: 'PALM',
  //       },
  //       createdAt: '14/06/2022',
  //     },
  //     user: {
  //       id: 1,
  //       firstName: 'Esthera',
  //       lastName: 'Jackson',
  //       email: 'alecthompson@mail.com',
  //       phone: '+14898903328',
  //       birthday: '14/06/1991',
  //       role: 4,
  //       status: 1,
  //       createdAt: '17/09/2021',
  //       asset: '',
  //       address: {
  //         address1: '96607 Claire Square Suite',
  //         address2: 'St. Louis Park, HI',
  //         city: 'New York',
  //         state: '',
  //         country: 'USA',
  //         zipcode: '48021',
  //       },
  //     },
  //     location: {
  //       name: 'Palm Casino Resort',
  //       coords: { lat: 40.7127837, lng: -74.0059413 },
  //       id: 1,
  //       address: {
  //         address1: '',
  //         address2: '',
  //         city: 'New York',
  //         state: '',
  //         country: 'USA',
  //         zipcode: '',
  //       },
  //       status: 'OPEN',
  //       type: 'PAML',
  //     },
  //     status: 'Waiting',
  //     requestedAt: '14/06/2022',
  //   },
  //   model: ActivityModel.REQUEST,
  //   type: ActivityType.CREATE,
  //   status: 'Waiting',
  //   createdAt: '2022/11/22',
  // },
  // {
  //   id: 3,
  //   user: {
  //     id: 2,
  //     firstName: 'Alexa',
  //     lastName: 'Liras',
  //     email: 'alexa@gmail.com',
  //     phone: '+14898903328',
  //     birthday: '12/06/1971',
  //     role: 4,
  //     status: 1,
  //     createdAt: '16/09/2021',
  //     asset: '',
  //     address: {
  //       address1: '96607 Claire Square Suite',
  //       address2: 'St. Louis Park, HI',
  //       city: 'New York',
  //       state: '',
  //       country: 'USA',
  //       zipcode: '48021',
  //     },
  //   },
  //   victim: {
  //     id: 1,
  //     item: {
  //       id: 6,
  //       product: {
  //         id: 6,
  //         name: 'Marshal V6',
  //         point: 39000,
  //         short: '128gb RAM $600',
  //         description: '',
  //         amount: 3,
  //         status: ActivityType.CREATE,
  //         createdAt: '14/06/2022',
  //       },
  //       locationId: 0,
  //       location: {
  //         name: 'Palm Casino Resort',
  //         coords: { lat: 40.7127837, lng: -74.0059413 },
  //         id: 1,
  //         address: {
  //           address1: '',
  //           address2: '',
  //           city: '',
  //           state: 'New York',
  //           zipcode: '',
  //           country: 'USA',
  //         },
  //         status: 'OPEN',
  //         type: 'Palm',
  //       },
  //       createdAt: '14/06/2022',
  //     },
  //     user: {
  //       id: 1,
  //       firstName: 'Esthera',
  //       lastName: 'Jackson',
  //       email: 'alecthompson@mail.com',
  //       phone: '+14898903328',
  //       birthday: '14/06/1991',
  //       role: 4,
  //       status: 1,
  //       createdAt: '17/09/2021',
  //       asset: '',
  //       address: {
  //         address1: '96607 Claire Square Suite',
  //         address2: 'St. Louis Park, HI',
  //         city: 'New York',
  //         state: '',
  //         country: 'USA',
  //         zipcode: '48021',
  //       },
  //     },
  //     location: {
  //       name: 'Palm Casino Resort',
  //       coords: { lat: 40.7127837, lng: -74.0059413 },
  //       id: 1,
  //       address: {
  //         address1: '',
  //         address2: '',
  //         city: 'New York',
  //         state: '',
  //         country: 'USA',
  //         zipcode: '',
  //       },
  //       status: 'OPEN',
  //       type: 'Palm',
  //     },
  //     status: 'Accepted',
  //     requestedAt: '14/06/2022',
  //   },
  //   model: ActivityModel.REQUEST,
  //   type: ActivityType.UPDATE,
  //   status: 'Accepted',
  //   createdAt: '2022/11/22',
  // },
];
