import { ActivityItemType } from '@/types';
import { ActivityModel, ActivityType } from '@/constants/Enum';

export const activityData: ActivityItemType[] = [
  {
    id: 1,
    user: {
      id: 2,
      firstName: 'Alexa',
      lastName: 'Liras',
      email: 'alexa@gmail.com',
      phonenumber: '+14898903328',
      birthday: '12/06/1971',
      role: 4,
      status: 1,
      createdAt: '16/09/2021',
      asset: '',
      location: {
        address1: '96607 Claire Square Suite',
        address2: 'St. Louis Park, HI',
        city: 'New York',
        state: '',
        country: 'USA',
        zipcode: '48021',
      },
    },
    victim: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    model: ActivityModel.USER,
    action: ActivityType.CHECKIN,
    status: '1000 Point',
    createdAt: '2022/11/22',
  },
  {
    id: 2,
    user: {
      id: 2,
      firstName: 'Alexa',
      lastName: 'Liras',
      email: 'alexa@gmail.com',
      phonenumber: '+14898903328',
      birthday: '12/06/1971',
      role: 4,
      status: 1,
      createdAt: '16/09/2021',
      asset: '',
      location: {
        address1: '96607 Claire Square Suite',
        address2: 'St. Louis Park, HI',
        city: 'New York',
        state: '',
        country: 'USA',
        zipcode: '48021',
      },
    },
    victim: {
      id: 1,
      item: {
        id: 6,
        name: 'Marshal V6',
        urls: ['images/marshal.jpg'],
        location: {
          name: 'Palm Casino Resort',
          coordinates: { lat: 40.7127837, lng: -74.0059413 },
          id: 1,
          location: {
            address1: '',
            address2: '',
            city: '',
            state: 'New York',
            zipcode: '',
            country: 'USA',
          },
          status: true,
          type: 'Palm',
          urls: [
            'images/palm.png',
            'images/roulette.png',
            'images/palm.png',
            'images/roulette.png',
          ],
        },
        point: 39000,
        short: '128gb RAM $600',
        description: '',
        amount: 3,
        status: 'Available',
        createdAt: '14/06/2022',
      },
      user: {
        id: 1,
        firstName: 'Esthera',
        lastName: 'Jackson',
        email: 'alecthompson@mail.com',
        phonenumber: '+14898903328',
        birthday: '14/06/1991',
        role: 4,
        status: 1,
        createdAt: '17/09/2021',
        asset: '',
        location: {
          address1: '96607 Claire Square Suite',
          address2: 'St. Louis Park, HI',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '48021',
        },
      },
      location: {
        name: 'Palm Casino Resort',
        coordinates: { lat: 40.7127837, lng: -74.0059413 },
        id: 1,
        location: {
          address1: '',
          address2: '',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '',
        },
        status: true,
        type: 'Palm',
        urls: [
          'images/palm.png',
          'images/roulette.png',
          'images/palm.png',
          'images/roulette.png',
        ],
      },
      status: 'Waiting',
      requestedAt: '14/06/2022',
    },
    model: ActivityModel.REQUEST,
    action: ActivityType.CREATE,
    status: 'Waiting',
    createdAt: '2022/11/22',
  },
  {
    id: 3,
    user: {
      id: 2,
      firstName: 'Alexa',
      lastName: 'Liras',
      email: 'alexa@gmail.com',
      phonenumber: '+14898903328',
      birthday: '12/06/1971',
      role: 4,
      status: 1,
      createdAt: '16/09/2021',
      asset: '',
      location: {
        address1: '96607 Claire Square Suite',
        address2: 'St. Louis Park, HI',
        city: 'New York',
        state: '',
        country: 'USA',
        zipcode: '48021',
      },
    },
    victim: {
      id: 1,
      item: {
        id: 6,
        name: 'Marshal V6',
        urls: ['images/marshal.jpg'],
        location: {
          name: 'Palm Casino Resort',
          coordinates: { lat: 40.7127837, lng: -74.0059413 },
          id: 1,
          location: {
            address1: '',
            address2: '',
            city: '',
            state: 'New York',
            zipcode: '',
            country: 'USA',
          },
          status: true,
          type: 'Palm',
          urls: [
            'images/palm.png',
            'images/roulette.png',
            'images/palm.png',
            'images/roulette.png',
          ],
        },
        point: 39000,
        short: '128gb RAM $600',
        description: '',
        amount: 3,
        status: 'Available',
        createdAt: '14/06/2022',
      },
      user: {
        id: 1,
        firstName: 'Esthera',
        lastName: 'Jackson',
        email: 'alecthompson@mail.com',
        phonenumber: '+14898903328',
        birthday: '14/06/1991',
        role: 4,
        status: 1,
        createdAt: '17/09/2021',
        asset: '',
        location: {
          address1: '96607 Claire Square Suite',
          address2: 'St. Louis Park, HI',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '48021',
        },
      },
      location: {
        name: 'Palm Casino Resort',
        coordinates: { lat: 40.7127837, lng: -74.0059413 },
        id: 1,
        location: {
          address1: '',
          address2: '',
          city: 'New York',
          state: '',
          country: 'USA',
          zipcode: '',
        },
        status: true,
        type: 'Palm',
        urls: [
          'images/palm.png',
          'images/roulette.png',
          'images/palm.png',
          'images/roulette.png',
        ],
      },
      status: 'Accepted',
      requestedAt: '14/06/2022',
    },
    model: ActivityModel.REQUEST,
    action: ActivityType.UPDATE,
    status: 'Accepted',
    createdAt: '2022/11/22',
  },
];
