import { RequestItemType } from '@/types';

export const requestsData: RequestItemType[] = [
  {
    id: 1,
    item: {
      id: 6,
      name: 'Marshal V6',
      url: ['images/marshal.jpg'],
      location: 'Mariland, USA',
      point: 39000,
      specifications: { price: 600, color: 'Silver/Black' },
      status: 'Available',
      createdAt: '14/06/2022',
    },
    user: {
      id: 1,
      name: 'Esthera Jackson',
      email: 'alecthompson@mail.com',
      phonenumber: '+14898903328',
      birthday: '14/06/1991',
      role: 4,
      status: 1,
      createdAt: '17/09/2021',
      asset: '',
      location: '96607 Claire Square Suite 591 - St. Louis Park, HI / 40802',
    },
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: 'New York, USA',
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    status: 'Pending',
    requestedAt: '14/06/2022',
  },
  {
    id: 2,
    item: {
      id: 2,
      name: 'Marshal V6',
      url: ['images/marshal.jpg'],
      location: 'Mariland, USA',
      point: 19000,
      specifications: { price: 600, color: 'Silver/Black' },
      status: 'Available',
      createdAt: '14/06/2022',
    },
    user: {
      id: 2,
      name: 'Alexa Liras',
      email: 'alexa@gmail.com',
      phonenumber: '+14898903328',
      birthday: '12/06/1971',
      role: 4,
      status: 1,
      createdAt: '16/09/2021',
      asset: '',
      location: '96607 Claire Square Suite 591 - St. Louis Park, HI / 40802',
    },
    location: {
      name: 'Roulette Casino Resort',
      coordinates: { lat: 34.0522342, lng: -118.2436849 },
      id: 2,
      location: 'California, USA',
      status: true,
      type: 'Roulette',
      urls: ['images/roulette.png'],
    },
    status: 'Accepted',
    requestedAt: '14/06/2022',
  },
];
