import { RewardItemType } from '@/types';

export const rewardsData: RewardItemType[] = [
  {
    id: 1,
    name: 'AirPods 2',
    url: ['images/earphone.jpg'],
    location: 'Mariland, USA',
    point: 12000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 2,
    name: 'Marshal V6',
    url: ['images/marshal.jpg'],
    location: 'Mariland, USA',
    point: 19000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 3,
    name: 'AppleWatch 8',
    url: ['images/iwatch.jpg'],
    location: 'Mariland, USA',
    point: 23000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 4,
    name: 'iPhone 14 pro',
    url: ['images/iphone.jpg'],
    location: 'Mariland, USA',
    point: 30000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 5,
    name: 'AirPods 2',
    url: ['images/earphone.jpg'],
    location: 'Mariland, USA',
    point: 32000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 6,
    name: 'Marshal V6',
    url: ['images/marshal.jpg'],
    location: 'Mariland, USA',
    point: 39000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 7,
    name: 'AppleWatch 8',
    url: ['images/iwatch.jpg'],
    location: 'Mariland, USA',
    point: 43000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 8,
    name: 'iPhone 14 pro',
    url: ['images/iphone.jpg'],
    location: 'Mariland, USA',
    point: 50000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 9,
    name: 'iPhone 14 pro',
    url: ['images/iphone.jpg'],
    location: 'Mariland, USA',
    point: 60000,
    specifications: { price: 600, color: 'Silver/Black' },
    status: 'Available',
    createdAt: '14/06/2022',
  },
];
