import { RewardItemType } from '@/types';

export const rewardsData: RewardItemType[] = [
  {
    id: 1,
    name: 'AirPods 2',
    urls: ['images/earphone.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 12000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 2,
    name: 'Marshal V6',
    urls: ['images/marshal.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 19000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 3,
    name: 'AppleWatch 8',
    urls: ['images/iwatch.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 23000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 4,
    name: 'iPhone 14 pro',
    urls: ['images/iphone.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 30000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 5,
    name: 'AirPods 2',
    urls: ['images/earphone.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 32000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 6,
    name: 'Marshal V6',
    urls: ['images/marshal.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 39000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 7,
    name: 'AppleWatch 8',
    urls: ['images/iwatch.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 43000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 8,
    name: 'iPhone 14 pro',
    urls: ['images/iphone.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 50000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
  {
    id: 9,
    name: 'iPhone 14 pro',
    urls: ['images/iphone.jpg'],
    location: {
      name: 'Palm Casino Resort',
      coordinates: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      location: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: true,
      type: 'Palm',
      urls: [
        'images/palm.png',
        'images/roulette.png',
        'images/palm.png',
        'images/roulette.png',
      ],
    },
    point: 60000,
    short: '128gb RAM $600',
    description: '',
    amount: 3,
    status: 'Available',
    createdAt: '14/06/2022',
  },
];
