import { ProductStatus } from '@/constants';
import { Reward } from '@/types';

export const rewardsData: Reward.Data[] = [
  {
    id: 1,
    product: {
      id: 1,
      name: 'AirPods 2',
      // point: 12000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 2,
    product: {
      id: 2,
      name: 'Marshal V6',
      // point: 19000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 3,
    product: {
      id: 3,
      name: 'AppleWatch 8',
      // point: 23000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 4,
    product: {
      id: 4,
      name: 'iPhone 14 pro',
      // point: 30000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 5,
    product: {
      id: 5,
      name: 'AirPods 2',
      // point: 32000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 6,
    product: {
      id: 6,
      name: 'Marshal V6',
      // point: 39000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 7,
    product: {
      id: 7,
      name: 'AppleWatch 8',
      // point: 43000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 8,
    product: {
      id: 8,
      name: 'iPhone 14 pro',
      // point: 50000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
  {
    id: 9,
    product: {
      id: 9,
      name: 'iPhone 14 pro',
      // point: 60000,
      short: '128gb RAM $600',
      description: '',
      amount: 3,
      status: ProductStatus.AVAILABLE,
      createdAt: '14/06/2022',
    },
    locationId: 0,
    location: {
      name: 'Palm Casino Resort',
      coords: { lat: 40.7127837, lng: -74.0059413 },
      id: 1,
      address: {
        address1: '',
        address2: '',
        city: '',
        state: 'New York',
        zipcode: '',
        country: 'USA',
      },
      status: 'OPEN',
      type: 'Palm',
    },
  },
];
